#      NetHack Datafiles Makefile.dat $NHDT-Date: 1596486993 2020/08/03 20:36:33 $ $NHDT-Branch: NetHack-5.0 $:$NHDT-Revision: 1.32 $
# Copyright (c) 2018 by Pasi Kallinen
# NetHack may be freely redistributed.  See license for details.

# Root of source tree:
NHSROOT=..

VARDAT = bogusmon data engrave epitaph rumors oracles

all:	$(VARDAT) spec_levs quest_levs

../util/makedefs:
	(cd ../util ; $(MAKE) makedefs)

nhdat: $(DATDLB)
	( LC_ALL=C ; ../util/dlb cf nhdat $(DATDLB) )

data:	data.base ../util/makedefs
	../util/makedefs -d

rumors:	rumors.tru rumors.fal ../util/makedefs
	../util/makedefs -r

oracles:	oracles.txt ../util/makedefs
	../util/makedefs -h

engrave:	engrave.txt ../util/makedefs
	../util/makedefs -2

epitaph:	epitaph.txt ../util/makedefs
	../util/makedefs -1

bogusmon:	bogusmon.txt ../util/makedefs
	../util/makedefs -3

options:	../util/makedefs
	../util/makedefs -v

# these don't actually do anything useful now that levcomp and dngcomp are gone
spec_levs:
	touch spec_levs
quest_levs:
	touch quest_levs

# gitinfo.txt is optionally made by src/Makefile when creating date.h
# spec_levs and quest_levs are empty marker files to control 'make' actions
clean:
	-rm -f spec_levs quest_levs gitinfo.txt

spotless: clean
	-rm -f nhdat $(VARDAT)

#eof#
